---
pack: gc_remediations
ref: gc_remediations.risk_trigger
name: risk_trigger
uid: rule:gc_remediations:risk_trigger
tags: []
type:
  ref: standard
  parameters: {}
enabled: true
trigger:
  type: nagios.service_state_change
  ref: nagios.service_state_change
  description: Trigger type for nagios service state change event.
  parameters: {}
metadata_file: ''
context:
  user: st2admin
criteria:
  trigger.state:
    pattern: "^OK|WARNING|CRITICAL$"
    type: regex
  trigger.state_type:
    pattern: HARD
    type: eq
  trigger.service:
    pattern: cross_margin_risk
    type: eq
action:
  ref: gc_remediations.remediate_risk
  description: try to auto remediate risk value
  parameters:
    down_device: "{{ trigger.host }}"
