---
pack: gc_remediations
ref: gc_remediations.swap_trigger
name: swap_trigger
uid: rule:gc_remediations:swap_trigger
tags: []
type:
  ref: standard
  parameters: {}
enabled: true
trigger:
  type: nagios.service_state_change
  ref: nagios.service_state_change
  description: Trigger type for nagios service state change event.
  parameters: {}
metadata_file: ''
context:
  user: st2admin
criteria:
  trigger.state:
    pattern: "^CRITICAL|WARNING$"
    type: regex
  trigger.state_type:
    pattern: HARD
    type: eq
  trigger.service:
    pattern: Swap
    type: eq
action:
  ref: gc_remediations.remediate_swap
  description: try to auto remediate swap space
  parameters:
    down_device: "{{ trigger.host }}"
